#设置默认的环境
spring:
  profiles:
    active: test

---

#开发
spring:
  profiles: dev
server:
  port: 8000

---

#生产
spring:
  profiles: pro
server:
  port: 8080

---

#测试
spring:
  profiles: test
server:
  port: 9000
